#!/usr/bin/env python3
"""bench.py -- measures the four spike gates for the Godot rung-4 lane.

Stdlib only. Mirrors nodeworld/bench.py in spirit. Writes bench_results.json and
prints a PASS/FAIL summary. Run:  python bench.py

Gates (see godotworld/SPIKE_REPORT.md):
  (a) BOOT        -- steady-state `godot --headless -s boot.gd` <= 2s (5 runs, warmed)
  (b) BATCH       -- 20 episodes x 120 ticks in ONE process, total wall <= 5s
  (c) DETERMINISM -- same job, fresh processes -> byte-identical JSONL, x5;
                     tested for BOTH stock Godot Physics 2D and Rapier2D
  (d) STATE       -- per-tick state under gravity: ball falls & rests; report rest y
"""

import json
import os
import shutil
import statistics
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
GODOT = os.path.join(HERE, "tools", "Godot_v4.7-stable_win64_console.exe")
STOCK_PROJ = HERE
RAPIER_PROJ = os.path.join(HERE, "tools", "rapier_project")
JOBDIR = os.path.join(HERE, "tools", "_jobs")

BEGIN = b"__JSONL_BEGIN__"
END = b"__JSONL_END__"

FLOOR_TOP = 60.0   # must match runner.gd
BALL_R = 20.0
BOX_HALF = 20.0

ACTION_SET = ["left", "right", "up", "none"]


# --------------------------------------------------------------------------- #
# Godot process helpers
# --------------------------------------------------------------------------- #
def run_godot(project, script, user_args=None, stdin_bytes=None, timeout=180):
    argv = [GODOT, "--headless", "--fixed-fps", "60", "--path", project, "-s", "res://" + script]
    if user_args:
        argv.append("--")
        argv += user_args
    t0 = time.perf_counter()
    proc = subprocess.run(
        argv, input=stdin_bytes, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=timeout
    )
    dt = time.perf_counter() - t0
    return dt, proc.stdout, proc.stderr, proc.returncode


def slice_jsonl_bytes(stdout):
    i = stdout.find(BEGIN)
    j = stdout.find(END)
    if i < 0 or j < 0:
        return None
    return stdout[i + len(BEGIN):j]


def sync_rapier_project():
    """Build the rapier project as the stock project + the physics_engine line.
    Keeps runner.gd single-source-of-truth (copied fresh); the addon is already in place.

    GOTCHA: a GDExtension only loads headless if res://.godot/extension_list.cfg exists,
    which is generated by a one-time editor import. So we run `--headless --import` once
    (idempotent) when that file is absent."""
    os.makedirs(RAPIER_PROJ, exist_ok=True)
    for f in ("runner.gd", "boot.gd", "diag.gd"):
        shutil.copyfile(os.path.join(STOCK_PROJ, f), os.path.join(RAPIER_PROJ, f))
    with open(os.path.join(STOCK_PROJ, "project.godot"), "r", encoding="utf-8") as fh:
        proj = fh.read()
    # Insert the rapier engine selector into the [physics] block.
    proj = proj.replace(
        "2d/run_on_separate_thread=false",
        '2d/physics_engine="Rapier2D"\n2d/run_on_separate_thread=false',
    )
    with open(os.path.join(RAPIER_PROJ, "project.godot"), "w", encoding="utf-8") as fh:
        fh.write(proj)
    ext_list = os.path.join(RAPIER_PROJ, ".godot", "extension_list.cfg")
    if not os.path.exists(ext_list):
        print("  (one-time) importing rapier project to register the GDExtension ...")
        subprocess.run(
            [GODOT, "--headless", "--import", "--path", RAPIER_PROJ],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=180,
        )


def write_job(name, job):
    os.makedirs(JOBDIR, exist_ok=True)
    path = os.path.join(JOBDIR, name)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(job, fh)
    return path


def make_batch_job(n_eps, n_ticks, frames_every=0):
    import random
    eps = []
    for e in range(n_eps):
        rng = random.Random(1000 + e)  # seeded so the job file is reproducible
        actions = [rng.choice(ACTION_SET) for _ in range(n_ticks)]
        eps.append({"seed": 1000 + e, "actions": actions})
    return {"episodes": eps, "max_ticks": n_ticks, "frames_every": frames_every}


# --------------------------------------------------------------------------- #
# Gate (a): BOOT
# --------------------------------------------------------------------------- #
def gate_boot():
    print("\n== Gate (a) BOOT ==")
    # Warmup (absorb Defender / cold FS cache).
    for _ in range(2):
        run_godot(STOCK_PROJ, "boot.gd", timeout=120)
    times = []
    for i in range(5):
        dt, out, err, rc = run_godot(STOCK_PROJ, "boot.gd", timeout=120)
        ok = b"BOOT_OK" in out
        times.append(dt)
        print("  run %d: %.3fs (rc=%d, printed=%s)" % (i + 1, dt, rc, ok))
    med = statistics.median(times)
    mn = min(times)
    result = {
        "runs_s": [round(t, 4) for t in times],
        "median_s": round(med, 4),
        "min_s": round(mn, 4),
        "gate_s": 2.0,
        "pass": med <= 2.0,
    }
    print("  median=%.3fs min=%.3fs -> %s (gate <=2s)" % (med, mn, "PASS" if result["pass"] else "FAIL"))
    return result


# --------------------------------------------------------------------------- #
# Gate (b): BATCH throughput
# --------------------------------------------------------------------------- #
def gate_batch():
    print("\n== Gate (b) BATCH (20 eps x 120 ticks, one process) ==")
    job = make_batch_job(20, 120, frames_every=0)
    path = write_job("batch.json", job)
    total_steps = 20 * 120 * 6
    times = []
    n_records = None
    for i in range(3):
        dt, out, err, rc = run_godot(STOCK_PROJ, "runner.gd", ["--job=" + path], timeout=180)
        body = slice_jsonl_bytes(out)
        recs = body.decode("utf-8").strip().splitlines() if body else []
        n_records = len(recs)
        times.append(dt)
        print("  run %d: %.3fs  (%d records, rc=%d)" % (i + 1, dt, n_records, rc))
    med = statistics.median(times)
    mn = min(times)
    result = {
        "episodes": 20, "ticks": 120, "physics_steps": total_steps,
        "records": n_records,
        "runs_s": [round(t, 4) for t in times],
        "median_s": round(med, 4), "min_s": round(mn, 4),
        "steps_per_s": round(total_steps / mn, 1) if mn > 0 else None,
        "gate_s": 5.0,
        "pass": med <= 5.0 and n_records == 20,
    }
    print("  median=%.3fs min=%.3fs (~%s steps/s incl boot) -> %s (gate <=5s)"
          % (med, mn, result["steps_per_s"], "PASS" if result["pass"] else "FAIL"))
    return result


# --------------------------------------------------------------------------- #
# Gate (c): DETERMINISM (stock + rapier)
# --------------------------------------------------------------------------- #
def determinism_for(project, label, job_path, n=5):
    print("  [%s] %d fresh processes, same job ..." % (label, n))
    bodies = []
    rc_ok = True
    for i in range(n):
        dt, out, err, rc = run_godot(project, "runner.gd", ["--job=" + job_path], timeout=180)
        body = slice_jsonl_bytes(out)
        if body is None:
            print("    run %d: NO JSONL (rc=%d) stderr=%s" % (i + 1, rc, err[-400:].decode("utf-8", "replace")))
            rc_ok = False
        bodies.append(body)
    all_same = rc_ok and all(b is not None and b == bodies[0] for b in bodies)
    size = len(bodies[0]) if bodies and bodies[0] else 0
    print("    -> %s (%d bytes/run, %d runs)" % ("byte-identical" if all_same else "DIVERGED", size, n))
    return {"pass": all_same, "bytes": size, "runs": n}, bodies[0]


def check_engine_live(project, label):
    dt, out, err, rc = run_godot(project, "diag.gd", timeout=120)
    line = None
    for ln in out.decode("utf-8", "replace").splitlines():
        if ln.startswith("__DIAG__"):
            line = ln[len("__DIAG__"):]
    facts = json.loads(line) if line else {"error": "no diag line"}
    print("  [%s] backend facts: %s" % (label, facts))
    return facts


def gate_determinism():
    print("\n== Gate (c) DETERMINISM ==")
    sync_rapier_project()
    # A physics-rich job: 20 eps x 60 ticks (fast but exercises contacts/rest).
    job = make_batch_job(20, 60, frames_every=0)
    path = write_job("det.json", job)

    stock_facts = check_engine_live(STOCK_PROJ, "stock")
    rapier_facts = check_engine_live(RAPIER_PROJ, "rapier")

    stock_res, stock_body = determinism_for(STOCK_PROJ, "stock", path, n=5)
    rapier_res, rapier_body = determinism_for(RAPIER_PROJ, "rapier", path, n=5)

    engines_differ = (stock_body is not None and rapier_body is not None
                      and stock_body != rapier_body)
    print("  stock vs rapier outputs differ (sanity they are distinct engines): %s" % engines_differ)

    at_least_one = stock_res["pass"] or rapier_res["pass"]
    result = {
        "stock": {**stock_res, "backend_facts": stock_facts},
        "rapier": {**rapier_res, "backend_facts": rapier_facts},
        "engines_differ": engines_differ,
        "pass": at_least_one,
    }
    print("  -> stock=%s rapier=%s  gate(>=1 byte-stable)=%s"
          % (stock_res["pass"], rapier_res["pass"], "PASS" if at_least_one else "FAIL"))
    return result


# --------------------------------------------------------------------------- #
# Gate (d): STATE READBACK
# --------------------------------------------------------------------------- #
def gate_state(project=STOCK_PROJ, label="stock"):
    print("\n== Gate (d) STATE READBACK (%s) ==" % label)
    # Pure drop: 40 ticks of "none" -> ball & box fall under gravity and rest.
    job = {"episodes": [{"seed": 7, "actions": ["none"] * 40}], "max_ticks": 40, "frames_every": 1}
    path = write_job("state_%s.json" % label, job)
    dt, out, err, rc = run_godot(project, "runner.gd", ["--job=" + path], timeout=120)
    body = slice_jsonl_bytes(out)
    rec = json.loads(body.decode("utf-8").strip().splitlines()[0])
    frames = rec["frames"]
    ys_ball = [(f["tick"], f["entities"]["ball"]["pos"][1]) for f in frames]
    ball_rest = ys_ball[-1][1]
    box_rest = frames[-1]["entities"]["box"]["pos"][1]
    ideal = FLOOR_TOP + BALL_R  # 80
    ideal_box = FLOOR_TOP + BOX_HALF  # 80
    pen_ball = ideal - ball_rest      # >0 = ball sank below ideal contact (slop)
    pen_box = ideal_box - box_rest
    # plausibility: y decreases monotonically until near rest, then settles
    start_y = ys_ball[0][1]
    fell = ball_rest < start_y - 100
    settled = abs(frames[-1]["entities"]["ball"]["vel"][1]) < 1.0
    print("  ball: start_y=%.2f -> rest_y=%.5f (ideal=%.1f, penetration=%.5f px)"
          % (start_y, ball_rest, ideal, pen_ball))
    print("  box : rest_y=%.5f (ideal=%.1f, penetration=%.5f px)" % (box_rest, ideal_box, pen_box))
    print("  first 8 ticks ball.y: %s" % [(t, round(y, 2)) for t, y in ys_ball[:8]])
    print("  fell>100px=%s  final|vy|<1=%s" % (fell, settled))
    result = {
        "ball_start_y": round(start_y, 4),
        "ball_rest_y": round(ball_rest, 6),
        "ball_penetration_px": round(pen_ball, 6),
        "box_rest_y": round(box_rest, 6),
        "box_penetration_px": round(pen_box, 6),
        "ideal_rest_y": ideal,
        "fell": fell, "settled": settled,
        "pass": fell and settled,
    }
    print("  -> %s" % ("PASS" if result["pass"] else "FAIL"))
    return result


# --------------------------------------------------------------------------- #
# stdin probe (report-only gotcha check)
# --------------------------------------------------------------------------- #
def probe_stdin():
    print("\n== stdin delivery probe (report note) ==")
    job = {"episodes": [{"seed": 1, "actions": ["none"] * 3}], "max_ticks": 3, "frames_every": 0}
    payload = json.dumps(job).encode("utf-8")
    try:
        dt, out, err, rc = run_godot(STOCK_PROJ, "runner.gd", stdin_bytes=payload, timeout=60)
        body = slice_jsonl_bytes(out)
        ok = body is not None and b'"result"' in body and b'"error":null' in body
        print("  stdin job -> %s" % ("delivered OK" if ok else "FAILED/empty"))
        return {"works": bool(ok)}
    except Exception as e:
        print("  stdin probe error: %s" % e)
        return {"works": False, "error": str(e)}


# --------------------------------------------------------------------------- #
def main():
    assert os.path.exists(GODOT), "Godot binary missing: %s" % GODOT
    print("Godot:", GODOT)
    results = {}
    results["godot_version"] = subprocess.run(
        [GODOT, "--version"], stdout=subprocess.PIPE).stdout.decode().strip()
    results["boot"] = gate_boot()
    results["batch"] = gate_batch()
    results["determinism"] = gate_determinism()
    results["state_stock"] = gate_state(STOCK_PROJ, "stock")
    results["state_rapier"] = gate_state(RAPIER_PROJ, "rapier")
    results["stdin_probe"] = probe_stdin()

    with open(os.path.join(HERE, "bench_results.json"), "w", encoding="utf-8") as fh:
        json.dump(results, fh, indent=2)

    print("\n==================== SUMMARY ====================")
    print("Godot: %s" % results["godot_version"])
    print("(a) BOOT        : %s  (median %.3fs, gate <=2s)"
          % ("PASS" if results["boot"]["pass"] else "FAIL", results["boot"]["median_s"]))
    print("(b) BATCH       : %s  (median %.3fs, gate <=5s)"
          % ("PASS" if results["batch"]["pass"] else "FAIL", results["batch"]["median_s"]))
    d = results["determinism"]
    print("(c) DETERMINISM : %s  (stock=%s, rapier=%s)"
          % ("PASS" if d["pass"] else "FAIL", d["stock"]["pass"], d["rapier"]["pass"]))
    print("(d) STATE       : %s  (ball rest_y=%.4f, pen=%.4f px)"
          % ("PASS" if results["state_stock"]["pass"] else "FAIL",
             results["state_stock"]["ball_rest_y"], results["state_stock"]["ball_penetration_px"]))
    print("stdin delivers  : %s" % results["stdin_probe"]["works"])
    print("wrote bench_results.json")


if __name__ == "__main__":
    main()
